### ISSUE TITLE
Google/system calendar sync

### ISSUE THREAD

**Issue by luxcalor** [davemorrissey/sundroid#2]
Could you please allow an option for selected data from the app to show on the Google calendar. That would be very helpful! Thanks.

**Comment by davemorrissey** [comment]
Thanks for the suggestion! I'll look into that, unfortunately I haven't had time since the pandemic started to work on the app so I have a backlog of features to work on.

**Comment by luxcalor** [comment]
Thanks! If it comes to implementing this feature, Sundroid will probably be the only sun related Android app to have it. Couldn't find it anywhere else. Thanks for a great app and keep up the good work.
